Repository student-techlife/IPMEDT4-binnentuin-frontend, pull requests merged in 2020-06, with the labels that each got.

#10 🐳 Start using devcontainers!
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/deploy.yml
  .vscode/tasks.json
  package-lock.json
Labels: 🔍 Ready for Review

#16 Home keuze
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/img/banner.jpg
  src/img/decoration.png
  src/img/logo_green.png
  src/img/logo_white.png
  src/pages/keuze/Keuze.jsx
  src/pages/keuze/Keuze.scss
  src/pages/keuze/Optie.js
  src/pages/keuze/OptieList.js
  src/scss/_default.scss
  src/scss/_var.scss
Labels: ✅ Approved

#18 🔨 Auto assign member to PR
  .github/reviewer-lottery.yml
  .github/workflows/review-assign.yml
  _redirects
  package.json
  src/App.js
  src/pages/errors/404.jsx
Labels: 🔍 Ready for Review

#21 Home fixes
  src/pages/keuze/Keuze.scss
  src/pages/keuze/Optie.js
Labels: ✅ Approved

#26 Beginning of pre-test corona
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/assets/scss/_var.scss
  src/img/background_flower.png
  src/pages/pre-test/Pretest.jsx
  src/pages/pre-test/Pretest.scss
Labels: 🔍 Ready for Review

#30 Keuze eten
  package-lock.json
  package.json
  src/App.js
  src/pages/binnentuin/menu/Card.js
  src/pages/binnentuin/menu/CardList.js
  src/pages/binnentuin/menu/Menu.jsx
  src/pages/binnentuin/menu/Menu.scss
  src/pages/keuze/Keuze.jsx
Labels: ✅ Approved

#31 added menu + salads placeholder list
  src/pages/binnentuin/menu/CardListSalads.js
  src/pages/binnentuin/menu/Menu.jsx
  src/pages/binnentuin/menu/Menu.scss
Labels: ✅ Approved

#32 ✨ login en register voor klanten
  package-lock.json
  package.json
  src/App.js
  src/App.tsx
  src/components/common/router/protected/auth.js
  src/components/common/router/protected/index.tsx
  src/pages/auth/auth.scss
  src/pages/auth/inloggen.jsx
  src/pages/auth/registreren.jsx
  src/pages/profile/dashboard.jsx
  src/pages/styles.jsx
  src/react-app-env.d.ts
  src/services/AuthService.tsx
  src/services/CookieService.tsx
  src/services/UrlService.tsx
  tsconfig.json
Labels: ✅ Approved

#39 🔨 Los probleem op met font-size overrule
  src/assets/scss/_default.scss
  src/pages/binnentuin/menu/Menu.jsx
  src/pages/binnentuin/menu/Menu.scss
  src/pages/pre-test/Pretest.scss
  src/pages/tijd/Tijd.scss
  yarn.lock
Labels: ✅ Approved

#43 Verbeterde Tijd.jsx en extra optie bij pretest
  src/pages/pre-test/Pretest.jsx
  src/pages/pre-test/Pretest.scss
  src/pages/tijd/Tijd.jsx
  src/pages/tijd/Tijd.scss
  src/pages/tijd/TijdCard.js
  src/pages/tijd/TijdCardList.js
Labels: ✅ Approved

#51 added ophaal choice + refactored keuze for reuse
  src/pages/Optie/Optie.js
  src/pages/Optie/Optie.scss
  src/pages/keuze/Keuze.scss
  src/pages/keuze/OptieList.js
  src/pages/pre-test/Pretest.jsx
  src/pages/pre-test/Pretest.scss
Labels: ✅ Approved

#49 pagina's koppelen
  src/components/header/Header.jsx
  src/pages/Optie/Optie.scss
  src/pages/keuze/Keuze.scss
  src/pages/keuze/OptieList.js
  src/pages/pre-test/Pretest.jsx
Labels: ✅ Approved

#58 Tijden opvragen
  package-lock.json
  package.json
  src/components/footer/Footer.jsx
  src/components/footer/Footer.scss
  src/pages/Optie/Optie.js
  src/pages/Optie/Optie.scss
  src/pages/keuze/OptieList.js
Labels: ✅ Approved, 🔍 Ready for Review

#48 ✨ Beginsel winkelmand pagina + UrlService convert
  src/App.tsx
  src/components/header/Header.jsx
  src/components/header/Header.scss
  src/pages/binnentuin/menu/CardList.js
  src/pages/binnentuin/menu/CardListBagels.js
  src/pages/binnentuin/menu/CardListSalads.js
  src/pages/binnentuin/menu/CardListSandwiches.js
  src/pages/binnentuin/menu/CardListToasts.js
  src/pages/binnentuin/menu/Menu.scss
  src/pages/keuze/OptieList.js
  src/pages/winkelmand/winkelmand.jsx
  src/services/UrlService.tsx
Labels: 🔍 Ready for Review

#59 CSS fix mobile + tablet
  src/pages/binnentuin/menu/Card.js
  src/pages/binnentuin/menu/Menu.scss
Labels: ✅ Approved

#62 Made header more responsive
  src/components/header/Header.jsx
  src/components/header/Header.scss
Labels: ✅ Approved

#63 Menu page css
  src/pages/binnentuin/menu/Menu.scss
Labels: ✅ Approved

#64 Pretest responsive
  src/assets/img/background_flower.png
  src/components/header/Header.scss
  src/pages/pre-test/Pretest.jsx
  src/pages/pre-test/Pretest.scss
Labels: ✅ Approved

#61 koppeling gemaakt met api
  package-lock.json
  src/components/footer/Footer.jsx
  src/pages/keuze/OptieList.js
  src/pages/pre-test/Pretest.jsx
  src/services/UrlService.tsx
Labels: 🔍 Ready for Review

#66 desktop css menu center + card more width
  src/pages/binnentuin/menu/Menu.scss
Labels: ✅ Approved

#67 Winkelwagen
  public/index.html
  src/App.tsx
  src/components/Recipe.js
  src/components/actions/action-types/cart-actions.js
  src/components/actions/cartActions.js
  src/components/reducers/cartReducer.js
  src/images/item1.jpg
  src/images/item2.jpg
  src/images/item3.jpg
  src/images/item4.jpg
  src/images/item5.jpg
  src/images/item6.jpg
  src/index.js
  src/pages/binnentuin/menu/CardList.js
  src/pages/binnentuin/menu/CardListBagels.js
  src/pages/binnentuin/menu/CardListSalads.js
  src/pages/binnentuin/menu/CardListSandwiches.js
  src/pages/binnentuin/menu/CardListToasts.js
  src/pages/binnentuin/menu/Menu.jsx
  src/pages/binnentuin/menu/Menu.scss
  src/pages/winkelmand/winkelmand.jsx
  src/pages/winkelmand/winkelmand.scss
Labels: ✅ Approved

#68 Route branch
  src/App.test.js
  src/App.tsx
  src/components/banner/Banner.scss
  src/components/header/Header.jsx
  src/components/header/Header.scss
Labels: ✅ Approved

#65 added submission of pretest form
  src/App.tsx
  src/pages/contact/Contact.jsx
  src/pages/contact/Contact.scss
  src/pages/keuze/Keuze.scss
  src/pages/keuze/OptieList.js
  src/pages/pre-test/Pretest.jsx
  src/pages/pre-test/Pretest.scss
  src/services/UrlService.tsx
Labels: 🔍 Ready for Review

#69 Roof page toegevoegd
  src/App.tsx
  src/pages/binnentuin/menu/Menu.scss
  src/pages/keuze/OptieList.js
  src/pages/theRoof/CardListRoof.js
  src/pages/theRoof/CardRoof.js
  src/pages/theRoof/MenuRoof.jsx
Labels: ✅ Approved

#71 ✨ items van the roof komen in winkelmand
  src/App.tsx
  src/pages/binnentuin/menu/Menu.jsx
  src/pages/keuze/OptieList.js
  src/pages/theRoof/MenuRoof.jsx
Labels: ✅ Approved

#70 Contact pagina responsive en contact link in footer
  src/components/footer/Footer.jsx
  src/components/footer/Footer.scss
  src/pages/contact/Contact.jsx
  src/pages/contact/Contact.scss
Labels: ✅ Approved
